"""Long Video (story) endpoints.

Backs the panel's "Long Video" mode: a 20–60s request is planned into scenes
(every provider clip maxes out well below 20s, so a long video is per-scene
clips merged with ffmpeg):

  1. POST /story/plan          — LLM turns the idea + total duration into a
                                 story and N scenes (duration + image prompt
                                 each; durations sum to the total).
  2. POST /story/video-prompts — LLM writes per-scene image-to-video motion
                                 prompts from the story + confirmed images.
  3. POST /story/merge         — downloads the per-scene clips, concatenates
                                 them with ffmpeg and stores the result as a
                                 normal video Item (SSE events like
                                 /generate/video: started/processing/…).

Scene images and clips themselves are generated by the existing
/generate/image and /generate/video endpoints — the frontend drives one call
per scene and tracks them by generation_id.

LLM access mirrors /prompt/rewrite: OpenAI primary, Gemini fallback, keys from
the OPENAI_KEY / GOOGLE_AI_API_KEY plugin secrets.
"""

from __future__ import annotations

import asyncio
import base64
import functools
import json
import logging
import mimetypes
import os
import re
import shutil
import tempfile
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import unquote, urlparse

import anyio
import httpx
from fastapi import Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel

from palette_sdk import (
    PluginContext,
    PluginRouter,
    require_permission,
)

from backend.api.core.org_db import get_ctx

from backend.api.db_helpers import (
    create_initial_item,
    delete_story_session,
    get_asset,
    get_asset_by_url,
    get_items_by_generation_id,
    get_key_frame,
    get_project,
    list_story_sessions,
    set_asset_analysis,
    set_item_fields,
    touch_project,
    update_item_failed,
    update_item_success,
    upsert_story_session,
)
from backend.api.core.bg_session import standalone_background_session
from backend.api.core.secrets import read_secret
from backend.api.core.sse_manager import bind_user_id, broadcast_event
from backend.api.core.storage_helper import generate_video_thumbnail_from_file
from backend.api.core.video_merge import (
    dimensions_for,
    extract_first_frame,
    ffmpeg_unavailable_reason,
    find_ffmpeg,
    image_to_video,
    merge_videos,
    mux_final_audio,
    probe_duration,
    reencode_scene_video,
)
from backend.api.core import elevenlabs_helper

logger = logging.getLogger("pltt_creative_video.story_video")
router = PluginRouter(tags=["story-video"])

# Total-duration bounds for the Long Video mode.
_TOTAL_MIN, _TOTAL_MAX = 20, 60
# Preferred per-scene bounds the LLM plans within…
_SCENE_MIN, _SCENE_MAX = 3, 10
# …and the providers' actual per-clip ceiling (Kling/Seedance stop at 15s).
_HARD_SCENE_MAX = 15

# Merged output rides the normal video Item pipeline under this model name.
LONG_VIDEO_MODEL = "long_video"

_PLUGIN_BASE = "/api/v1/plugins/pltt-storyboard-video-maker"


# --- LLM plumbing (OpenAI primary, Gemini fallback, JSON output) -------------

def _parse_json_block(text: str) -> dict:
    t = (text or "").strip()
    t = re.sub(r"^```(?:json)?\s*|\s*```$", "", t, flags=re.IGNORECASE)
    start, end = t.find("{"), t.rfind("}")
    if start == -1 or end <= start:
        raise ValueError(f"no JSON object in LLM reply: {t[:200]!r}")
    return json.loads(t[start : end + 1])


async def _openai_json(api_key: str, system: str, user: str, model: str = "gpt-5.5") -> dict:
    model = os.getenv("AGENT_OPENAI_MODEL", model)
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {api_key}"},
            json={
                "model": model,
                "response_format": {"type": "json_object"},
                "messages": [
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
            },
        )
        r.raise_for_status()
        return _parse_json_block(r.json()["choices"][0]["message"]["content"])


async def _gemini_json(api_key: str, system: str, user: str, model: str = "gemini-3.1-pro") -> dict:
    model = os.getenv("AGENT_GEMINI_MODEL", model)
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
            headers={"x-goog-api-key": api_key},
            json={
                "system_instruction": {"parts": [{"text": system}]},
                "contents": [{"parts": [{"text": user}]}],
                "generationConfig": {"responseMimeType": "application/json"},
            },
        )
        r.raise_for_status()
        data = r.json()
        return _parse_json_block(data["candidates"][0]["content"]["parts"][0]["text"])


async def _anthropic_json(api_key: str, system: str, user: str, model: str) -> dict:
    model = os.getenv("AGENT_ANTHROPIC_MODEL", model)
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": model,
                "max_tokens": 8192,
                "system": system,
                "messages": [{"role": "user", "content": user}],
            },
        )
        r.raise_for_status()
        data = r.json()
        text = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
        return _parse_json_block(text)


# --- Session persistence ------------------------------------------------------
# The whole flow state (story, scenes with prompts/generation ids/urls,
# references, step, models — i.e. the outputs AND the inputs they were
# generated from) is snapshotted so a page refresh restores the board exactly.
# A key frame can hold SEVERAL story sessions at once — generating a new story
# must not hide the ones already on that key frame.

class StorySessionSaveRequest(BaseModel):
    id: str
    project_id: Optional[str] = None
    # The key frame the story was created on — the session shows only there.
    key_frame_id: Optional[str] = None
    data: Dict[str, Any]


@router.get(
    "/story/generation/{generation_id}",
    dependencies=[require_permission("resources:read")],
)
async def fetch_story_generation(
    generation_id: str,
    ctx: PluginContext = Depends(get_ctx),
):
    """Poll one generation batch's items by generation_id (no project needed).
    The standalone story flow uses this as a reliability net when an SSE
    'completed'/'failed' event is missed, so a run never stays stuck on
    'rendering'."""
    items = await get_items_by_generation_id(ctx.db, ctx.user_id, generation_id)
    return {"generation_id": generation_id, "count": len(items), "items": items}


@router.get("/story/session", dependencies=[require_permission("resources:read")])
async def fetch_story_sessions(
    project_id: Optional[str] = None,
    key_frame_id: Optional[str] = None,
    ctx: PluginContext = Depends(get_ctx),
):
    sessions = await list_story_sessions(
        ctx.db, ctx.user_id, project_id or None, key_frame_id or None
    )
    return {"sessions": sessions}


@router.put("/story/session", dependencies=[require_permission("resources:write")])
async def save_story_session(
    body: StorySessionSaveRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    if not (body.id or "").strip():
        raise HTTPException(status_code=400, detail="id is required")
    if not isinstance(body.data, dict) or not body.data:
        raise HTTPException(status_code=400, detail="data is required")
    saved = await upsert_story_session(
        ctx.db,
        organization_id=ctx.organization_id,
        user_id=ctx.user_id,
        session_id=body.id.strip(),
        project_id=(body.project_id or "").strip() or None,
        key_frame_id=(body.key_frame_id or "").strip() or None,
        data=body.data,
    )
    return {"status": "success", "session": saved}


@router.delete("/story/session/{session_id}", dependencies=[require_permission("resources:write")])
async def remove_story_session(
    session_id: str,
    ctx: PluginContext = Depends(get_ctx),
):
    ok = await delete_story_session(ctx.db, ctx.user_id, session_id)
    if not ok:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"status": "success"}


# --- Step 0: analyse reference images (characters/objects/backgrounds) -------

_ANALYZE_SYSTEM = """You analyse ONE reference image that will guide AI image generation for a multi-scene film.

Return ONLY a JSON object of this exact shape:
{"kind": "character" | "object" | "background" | "style" | "other", "name": "...", "description": "..."}

Rules:
- "kind": what the image primarily provides — a character (person/creature), an object/prop, a background/location, an overall art style, or other.
- "name": a short 1–3 word handle (e.g. "red-haired girl", "vintage taxi", "neon alley").
- "description": everything an image model needs to reproduce the subject IDENTICALLY in new scenes. Characters: apparent age, gender, face, hair, skin, build, wardrobe, accessories, distinguishing marks. Objects: shape, colors, materials, wear, markings. Backgrounds: setting, architecture, palette, lighting, era, weather. Styles: medium, technique, palette, mood.
- Describe only what is visible; be concrete and specific."""


async def _fetch_image_b64(url: str) -> tuple[str, str]:
    """Returns (base64_data, mime_type) for an image URL. Handles the local
    dev-storage file:// URLs the asset uploader hands out, plus data: URIs."""
    m = re.match(r"^data:(?P<type>[\w/+.-]+);base64,(?P<b64>.+)$", url, re.DOTALL)
    if m:
        return m.group("b64"), m.group("type")
    if url.startswith("file://"):
        path = Path(unquote(urlparse(url).path))
        data = path.read_bytes()
        mime = mimetypes.guess_type(path.name)[0] or "image/png"
        return base64.b64encode(data).decode("ascii"), mime
    async with httpx.AsyncClient(timeout=60, follow_redirects=True) as client:
        resp = await client.get(url)
        resp.raise_for_status()
        mime = (resp.headers.get("content-type") or "image/png").split(";")[0].strip()
        return base64.b64encode(resp.content).decode("ascii"), mime


async def _gemini_vision_json(
    api_key: str, system: str, text: str, image_b64: str, mime: str, model: str = "gemini-2.5-pro"
) -> dict:
    model = os.getenv("AGENT_GEMINI_MODEL", model)
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
            headers={"x-goog-api-key": api_key},
            json={
                "system_instruction": {"parts": [{"text": system}]},
                "contents": [
                    {
                        "parts": [
                            {"inline_data": {"mime_type": mime, "data": image_b64}},
                            {"text": text},
                        ]
                    }
                ],
                "generationConfig": {"responseMimeType": "application/json"},
            },
        )
        r.raise_for_status()
        data = r.json()
        return _parse_json_block(data["candidates"][0]["content"]["parts"][0]["text"])


async def _openai_vision_json(
    api_key: str, system: str, text: str, image_b64: str, mime: str, model: str = "gpt-5.5"
) -> dict:
    model = os.getenv("AGENT_OPENAI_MODEL", model)
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {api_key}"},
            json={
                "model": model,
                "response_format": {"type": "json_object"},
                "messages": [
                    {"role": "system", "content": system},
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": text},
                            {
                                "type": "image_url",
                                "image_url": {"url": f"data:{mime};base64,{image_b64}"},
                            },
                        ],
                    },
                ],
            },
        )
        r.raise_for_status()
        return _parse_json_block(r.json()["choices"][0]["message"]["content"])


async def _anthropic_vision_json(
    api_key: str, system: str, text: str, image_b64: str, mime: str, model: str = "claude-sonnet-5"
) -> dict:
    model = os.getenv("AGENT_ANTHROPIC_MODEL", model)
    async with httpx.AsyncClient(timeout=120) as client:
        r = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": model,
                "max_tokens": 8192,
                "system": system,
                "messages": [
                    {
                        "role": "user",
                        "content": [
                            {"type": "image", "source": {"type": "base64", "media_type": mime, "data": image_b64}},
                            {"type": "text", "text": text},
                        ],
                    }
                ],
            },
        )
        r.raise_for_status()
        data = r.json()
        out = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
        return _parse_json_block(out)


# User-selectable LLM for the writing steps (plan, motion prompts, chat) — maps
# the frontend's `llm` value to (secret name, model id, text call, vision
# call). "Latest" per model family as of this build: Opus 4.8, Sonnet 5,
# Haiku 4.5. Placed after the vision helpers above since the dict literal
# references them by name at import time.
_LLM_PROVIDERS: dict[str, tuple[str, str, Any, Any]] = {
    "claude_opus": ("ANTHROPIC_API_KEY", "claude-opus-4-8", _anthropic_json, _anthropic_vision_json),
    "claude_sonnet": ("ANTHROPIC_API_KEY", "claude-sonnet-5", _anthropic_json, _anthropic_vision_json),
    "claude_haiku": ("ANTHROPIC_API_KEY", "claude-haiku-4-5-20251001", _anthropic_json, _anthropic_vision_json),
    "gpt": ("OPENAI_KEY", "gpt-5.5", _openai_json, _openai_vision_json),
    "gemini": ("GOOGLE_AI_API_KEY", "gemini-3.1-pro", _gemini_json, _gemini_vision_json),
}
_DEFAULT_LLM = "gpt"


async def _llm_json(
    ctx: PluginContext,
    system: str,
    user: str,
    llm: Optional[str] = None,
    image_b64: Optional[str] = None,
    mime: Optional[str] = None,
) -> dict:
    """Text (or, with `image_b64`, vision) JSON call to the user-selected LLM,
    falling back through every other configured provider on failure."""
    llm = (llm or "").strip().lower()
    order = [llm] if llm in _LLM_PROVIDERS else []
    order += [p for p in _LLM_PROVIDERS if p not in order]  # try the rest as a fallback

    errors: list[str] = []
    for provider in order:
        secret_name, model, call, vision_call = _LLM_PROVIDERS[provider]
        api_key = read_secret(ctx, secret_name)
        if not api_key:
            continue
        try:
            if image_b64:
                return await vision_call(api_key, system, user, image_b64, mime or "image/png", model)
            return await call(api_key, system, user, model)
        except Exception as e:  # noqa: BLE001 — fall through to the next provider
            errors.append(f"{provider}: {e}")
            logger.warning("story LLM via %s failed: %s", provider, e)
    raise HTTPException(
        status_code=502,
        detail="; ".join(errors)
        or "No LLM configured (set ANTHROPIC_API_KEY, OPENAI_KEY, or GOOGLE_AI_API_KEY)",
    )


class ReferenceAnalyzeRequest(BaseModel):
    url: str
    asset_id: Optional[str] = None


def _clean_analysis(data: dict) -> dict:
    kind = str(data.get("kind") or "other").strip().lower()
    if kind not in {"character", "object", "background", "style", "other"}:
        kind = "other"
    return {
        "kind": kind,
        "name": str(data.get("name") or "reference").strip()[:80],
        "description": str(data.get("description") or "").strip()[:2000],
    }


@router.post("/story/reference/analyze", dependencies=[require_permission("resources:write")])
async def analyze_story_reference(
    body: ReferenceAnalyzeRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    """Analyses a reference image with a vision model (Gemini primary — the
    user-facing contract — OpenAI fallback) and persists {kind, name,
    description} on the asset row so the analysis rides content-hash dedup."""
    url = (body.url or "").strip()
    if not url:
        raise HTTPException(status_code=400, detail="url is required")

    # Already analysed (same asset re-used or re-uploaded) → reuse. Without an
    # asset_id, fall back to the URL — e.g. a video-mode start frame surfacing
    # in the Long Video references only knows its hosted URL.
    asset = None
    if body.asset_id:
        asset = await get_asset(ctx.db, ctx.user_id, body.asset_id)
    if asset is None:
        asset = await get_asset_by_url(ctx.db, ctx.user_id, url)
    if asset and isinstance(asset.get("analysis"), dict) and asset["analysis"].get("description"):
        return {"status": "cached", "analysis": asset["analysis"]}

    try:
        image_b64, mime = await _fetch_image_b64(url)
    except Exception as e:  # noqa: BLE001 — bad/unreachable reference URL
        raise HTTPException(status_code=400, detail=f"Could not fetch reference image: {e}")

    prompt = "Analyse this reference image for the film."
    errors: list[str] = []
    analysis: Optional[dict] = None
    gemini_key = read_secret(ctx, "GOOGLE_AI_API_KEY")
    if gemini_key:
        try:
            analysis = _clean_analysis(
                await _gemini_vision_json(gemini_key, _ANALYZE_SYSTEM, prompt, image_b64, mime)
            )
        except Exception as e:  # noqa: BLE001 — fall through to OpenAI
            errors.append(f"gemini: {e}")
            logger.warning("reference analysis via Gemini failed: %s", e)
    if analysis is None:
        openai_key = read_secret(ctx, "OPENAI_KEY")
        if openai_key:
            try:
                analysis = _clean_analysis(
                    await _openai_vision_json(openai_key, _ANALYZE_SYSTEM, prompt, image_b64, mime)
                )
            except Exception as e:  # noqa: BLE001
                errors.append(f"openai: {e}")
                logger.warning("reference analysis via OpenAI failed: %s", e)
    if analysis is None:
        raise HTTPException(
            status_code=502,
            detail="; ".join(errors)
            or "No vision LLM configured (set GOOGLE_AI_API_KEY or OPENAI_KEY)",
        )

    # Persist on the matched asset (by id or URL) so re-analyses stay cached.
    if asset:
        await set_asset_analysis(ctx.db, ctx.user_id, asset["id"], analysis)

    return {"status": "success", "analysis": analysis}


# --- Brand Kit: classify an uploaded brand asset (logo/character/palette/
# type/motion) so it lands in the right shelf without the user hand-picking a
# category. Reuses the same vision infra as the reference analyzer above,
# just with a brand-kit-specific prompt and category enum. ------------------

_BRANDKIT_CATEGORIES = (
    "logo", "character", "object", "color_palette", "typography", "motion_preset", "other",
)

_BRANDKIT_ANALYZE_SYSTEM = """You analyse ONE uploaded brand-kit asset for a video production team.

Return ONLY a JSON object of this exact shape:
{"category": "logo" | "character" | "object" | "color_palette" | "typography" | "motion_preset" | "other", "name": "...", "description": "..."}

Rules:
- "category": what the asset primarily IS, not what colors happen to appear in it —
  - "logo": a brand logo, wordmark, or symbol mark.
  - "character": a character, mascot, or person/creature reference sheet or artwork.
  - "object": a real-world product, prop, vehicle, item, or location/background photo used as a visual reference (e.g. a car, a bottle, a storefront). This is the default home for ordinary photos — pick this over "color_palette" whenever the image is a photo OF something rather than a chart of colors.
  - "color_palette": ONLY a dedicated swatch sheet, color chip grid, or hex-code chart whose entire purpose is presenting a set of brand colors — never a regular photo just because it's colorful.
  - "typography": a font specimen, type sample, or lettering reference.
  - "motion_preset": a reference for a camera move, transition, or animation style (not a still photo).
  - "other": anything that doesn't clearly fit the above (documents, textures, patterns, icons, etc.).
- "name": a short 1-4 word handle (e.g. "Ember wordmark", "HOBAN tiger mascot", "Red hatchback").
- "description": a concise, specific description an art director could use to apply this asset consistently across a video (colors, style, distinguishing traits).
- Describe only what is visible; be concrete and specific."""


def _clean_brandkit_analysis(data: dict) -> dict:
    category = str(data.get("category") or "other").strip().lower()
    if category not in _BRANDKIT_CATEGORIES:
        category = "other"
    return {
        "category": category,
        "name": str(data.get("name") or "asset").strip()[:80],
        "description": str(data.get("description") or "").strip()[:2000],
    }


class BrandKitAnalyzeRequest(BaseModel):
    url: str
    asset_id: Optional[str] = None


@router.post("/brandkit/analyze", dependencies=[require_permission("resources:write")])
async def analyze_brandkit_asset(
    body: BrandKitAnalyzeRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    """Analyses an uploaded Brand Kit asset with a vision model (Gemini
    primary, OpenAI fallback) and persists {category, name, description} on
    the asset row, mirroring analyze_story_reference but classifying into
    brand-kit shelves instead of story-reference kinds."""
    url = (body.url or "").strip()
    if not url:
        raise HTTPException(status_code=400, detail="url is required")

    asset = None
    if body.asset_id:
        asset = await get_asset(ctx.db, ctx.user_id, body.asset_id)
    if asset is None:
        asset = await get_asset_by_url(ctx.db, ctx.user_id, url)
    if asset and isinstance(asset.get("analysis"), dict) and asset["analysis"].get("description"):
        return {"status": "cached", "analysis": asset["analysis"]}

    try:
        image_b64, mime = await _fetch_image_b64(url)
    except Exception as e:  # noqa: BLE001 — bad/unreachable asset URL
        raise HTTPException(status_code=400, detail=f"Could not fetch asset image: {e}")

    prompt = "Analyse this brand-kit asset."
    errors: list[str] = []
    analysis: Optional[dict] = None
    gemini_key = read_secret(ctx, "GOOGLE_AI_API_KEY")
    if gemini_key:
        try:
            analysis = _clean_brandkit_analysis(
                await _gemini_vision_json(gemini_key, _BRANDKIT_ANALYZE_SYSTEM, prompt, image_b64, mime)
            )
        except Exception as e:  # noqa: BLE001 — fall through to OpenAI
            errors.append(f"gemini: {e}")
            logger.warning("brandkit analysis via Gemini failed: %s", e)
    if analysis is None:
        openai_key = read_secret(ctx, "OPENAI_KEY")
        if openai_key:
            try:
                analysis = _clean_brandkit_analysis(
                    await _openai_vision_json(openai_key, _BRANDKIT_ANALYZE_SYSTEM, prompt, image_b64, mime)
                )
            except Exception as e:  # noqa: BLE001
                errors.append(f"openai: {e}")
                logger.warning("brandkit analysis via OpenAI failed: %s", e)
    if analysis is None:
        raise HTTPException(
            status_code=502,
            detail="; ".join(errors)
            or "No vision LLM configured (set GOOGLE_AI_API_KEY or OPENAI_KEY)",
        )

    if asset:
        await set_asset_analysis(ctx.db, ctx.user_id, asset["id"], analysis)

    return {"status": "success", "analysis": analysis}


# --- Scene chat: ask questions, edit prompts, and (re)generate images via
# natural language, cross-referencing any scene in the SAME board by number,
# title or description ("make scene 3 look like the balloon one"). ----------

_CHAT_SYSTEM = """You are an on-set art director helping the user refine a multi-scene AI-generated storyboard, one scene at a time, through chat.

You are given: the overall story, its locked style bible, EVERY scene in the board (index, title, image prompt, whether it has a generated image yet), which scene is currently selected/focused, and the user's message. You may also be shown the selected scene's actual generated image.

The user's message can be:
- A QUESTION about the selected (or a mentioned) scene's image, its prompt, the story, or the style — just answer, no side effects.
- A request to CHANGE something about a scene's image (composition, color, mood, wardrobe, action, camera, wording, etc.) — rewrite that scene's image prompt to naturally incorporate the request, then regenerate it.
- A request to ONLY edit the prompt text without generating anything yet.
- A general "generate/make the images" request with no specific scene named — this means generate every scene that has no image yet.
- A reference to ANOTHER scene by number, title, or description (e.g. "like scene 2", "the one with the red umbrella", "@Scene 05") — resolve and target THAT scene instead of the selected one, matching against the provided scene list. If nothing else is referenced, target the selected scene.

Return ONLY a JSON object of this exact shape:
{"reply": "...", "action": "answer" | "update_prompt" | "regenerate" | "generate_all", "target_index": <int or null>, "new_prompt": "... or null"}

Rules:
- "reply": a short, friendly response to show in the chat (1–3 sentences), written in the same language as the user's message.
- "action":
  - "answer" — pure question or anything that isn't an image-edit/generate request. target_index and new_prompt are null.
  - "update_prompt" — rewrite the prompt but do NOT generate anything yet (only when the user explicitly says to just edit the text / not generate).
  - "regenerate" — rewrite the prompt (or keep the scene's current one unchanged if the user only asked to "regenerate"/"try again" with no edit) and generate a fresh image from it. This is the default action for any request that changes or redoes a specific scene's image.
  - "generate_all" — a general request with no specific scene named, to generate every scene that doesn't have an image yet.
- "target_index" is the 0-based index of the scene being changed — required for update_prompt/regenerate, null for answer/generate_all.
- "new_prompt", when present, is the FULL rewritten image prompt for that scene (not a diff or instruction) — apply the user's request on top of the scene's CURRENT image prompt, preserving its structure and any unrelated details. Leave it null if action is "regenerate" with no actual wording change requested, or if action is "answer"/"generate_all".
- NEVER put on-screen text into new_prompt (letters/words/numbers render misspelled and blurry in AI images) — convey meaning through composition, color and icons instead.
- If the message doesn't clearly ask to change or generate an image, default to "answer"."""


class StoryChatSceneIn(BaseModel):
    index: int
    title: Optional[str] = None
    image_prompt: str = ""
    has_image: bool = False


class StoryChatRequest(BaseModel):
    message: str
    story: Optional[str] = None
    bible: Optional[Dict[str, Any]] = None
    selected_index: int
    # The selected scene's generated image, if any — shown to a vision model
    # so questions about "this image" have real visual grounding.
    selected_image_url: Optional[str] = None
    scenes: List[StoryChatSceneIn]
    # Same user-selectable LLM as /story/plan and /story/video-prompts —
    # falls back through the other configured providers if unset/unavailable.
    llm: Optional[str] = None


def _bible_text(bible: Optional[Dict[str, Any]]) -> str:
    if not bible:
        return ""
    return "\n".join(f"{k}: {v}" for k, v in bible.items() if v)


@router.post("/story/chat", dependencies=[require_permission("resources:write")])
async def story_chat(
    body: StoryChatRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    """Chat-driven scene editing: answers questions about the selected scene's
    image/prompt, and can rewrite a scene's image prompt and/or trigger a
    (re)generation — targeting any scene in the board the user mentions, not
    just the selected one. The frontend executes the returned action locally
    (updateScene / regenerateImage / generateImages) so it reuses the exact
    same sequential-consistency generation pipeline as the manual buttons."""
    message = (body.message or "").strip()
    if not message:
        raise HTTPException(status_code=400, detail="message is required")
    if not body.scenes:
        raise HTTPException(status_code=400, detail="scenes is required")

    scenes_text = "\n".join(
        f'{s.index}. "{s.title or f"Scene {s.index + 1}"}" — '
        f'{"has image" if s.has_image else "NO image yet"} — prompt: {s.image_prompt}'
        for s in sorted(body.scenes, key=lambda s: s.index)
    )
    bible_block = _bible_text(body.bible)
    user_text = (
        f"Story: {body.story or ''}\n\n"
        + (f"Style bible:\n{bible_block}\n\n" if bible_block else "")
        + f"Scenes:\n{scenes_text}\n\n"
        f"Currently selected scene: {body.selected_index}\n\n"
        f"User message: {message}"
    )

    image_b64: Optional[str] = None
    mime: Optional[str] = None
    if body.selected_image_url:
        try:
            image_b64, mime = await _fetch_image_b64(body.selected_image_url)
        except Exception as e:  # noqa: BLE001 — fall back to text-only
            logger.warning("story chat: could not fetch selected image: %s", e)

    data = await _llm_json(ctx, _CHAT_SYSTEM, user_text, body.llm, image_b64, mime)

    action = str(data.get("action") or "answer").strip()
    if action not in {"answer", "update_prompt", "regenerate", "generate_all"}:
        action = "answer"
    valid_indices = {s.index for s in body.scenes}
    target_index = data.get("target_index")
    try:
        target_index = int(target_index) if target_index is not None else None
    except (TypeError, ValueError):
        target_index = None
    if target_index not in valid_indices:
        target_index = body.selected_index if action in {"update_prompt", "regenerate"} else None
    new_prompt = data.get("new_prompt")
    new_prompt = new_prompt.strip() if isinstance(new_prompt, str) and new_prompt.strip() else None

    return {
        "status": "success",
        "reply": str(data.get("reply") or "").strip(),
        "action": action,
        "target_index": target_index,
        "new_prompt": new_prompt,
    }


# --- Step 1: plan the story into scenes --------------------------------------

_PLAN_SYSTEM = f"""You are a film director planning a short AI-generated video from a user's idea.
Split the idea into sequential scenes that together tell one continuous story.

Return ONLY a JSON object of this exact shape:
{{"title": "...", "story": "...", "master_prompt": "...", "bible": {{"characters": "...", "environment": "...", "lighting": "...", "camera": "...", "grading": "..."}}, "scenes": [{{"title": "...", "duration": <int>, "image_prompt": "..."}}]}}

Rules:
- The top-level "title" is the film's display title: 2–5 words MAXIMUM (it must fit a narrow UI label), in the language of the user's idea. Never just repeat the idea text.
- Decide the number of scenes yourself from the total duration and the story's pacing.
- Each scene's "duration" is a whole number of seconds between {_SCENE_MIN} and {_SCENE_MAX}, and the durations MUST sum exactly to the requested total duration.
- "story" is a concise narrative (3–6 sentences) covering the full arc; write it in the language of the user's idea.
- "bible" is the film's LOCKED production design, in English, identical for every scene:
  - "characters": full identity of the recurring character(s)/subject — age, face, hair, build, wardrobe, distinguishing details.
  - "environment": world, location, weather, time of day, era.
  - "lighting": light sources, direction, mood.
  - "camera": lens (e.g. 85mm), camera height, shot distance, movement style, depth of field — never changes between scenes unless the story demands it.
  - "grading": color grade / film stock / overall visual style.
- "master_prompt" is a text-to-image prompt for ONE master reference image that locks the film's look: the bible's character(s) in a neutral, well-lit, front-facing composition in the bible's environment, lighting, lens and grading. No action, no story moment — it is a reference sheet the scene images will be generated FROM. Write it in English.
- "image_prompt" describes the scene's opening frame for a text-to-image model, in English. The bible carries identity and style — so focus each image_prompt on THIS scene's composition, action frozen mid-moment, framing and blocking; refer to bible entities briefly (e.g. "the sailor") without re-describing them.
- NO readable text anywhere: never put words, letters, numbers, signs with writing, banners, captions, labels or logos into "image_prompt", "master_prompt" or the bible (AI models render text misspelled and blurry). Convey meaning through icons, symbols, colors, gestures and composition instead — e.g. a hazard is marked by cones and a wordless warning icon, not a written sign.
- Each scene's "title" is a 2–5 word scene label."""

# Bible fields flattened into the GLOBAL STYLE block appended to prompts.
_BIBLE_FIELDS = ("characters", "environment", "lighting", "camera", "grading")


def _normalize_bible(raw: Any) -> dict:
    if not isinstance(raw, dict):
        return {}
    return {k: str(raw.get(k) or "").strip() for k in _BIBLE_FIELDS if str(raw.get(k) or "").strip()}


_PLAN_REFS_RULES = """
The user also provided numbered REFERENCE IMAGES (analysed below): the film's fixed cast, props, locations and/or style. Each is tagged with its kind — [character], [object], [background], or [style] — and each kind is used differently:
- [character] / [object] / [background] are literal visual elements to physically cast into the story. Additional rules:
  - Each scene object MUST also include "references": the list of reference numbers that scene uses (e.g. [1, 3]). Use [] only when no [character]/[object]/[background] reference is relevant to that scene.
  - Build the story around these referenced characters/objects/backgrounds — cast every one of them into the story and use it in every scene where the story calls for it.
  - When a scene uses reference N, its image_prompt MUST describe that entity using reference N's analysed description (repeat the look/wardrobe/details verbatim enough that the image model reproduces the reference faithfully) — never invent a different look for it.
- [style] references are NOT physical objects to place in any scene — never list them in a scene's "references", and never describe them as an object appearing in frame. Instead, fold what they establish into the film's LOCKED look:
  - A color-palette or grading style reference sets the "bible"'s "grading" field.
  - A typography/lettering style reference informs mood/texture only (remember: no readable text ever renders in image_prompt/master_prompt/bible regardless).
  - A camera-move/transition/motion style reference informs the "bible"'s "camera" field.
  - Write every scene's image_prompt so its mood, color and camera language already reflect these locked style choices — that's how a [style] reference gets "used", never as a literal cast element.
- The consistency of the referenced characters/objects/backgrounds/style and of the story always takes priority."""


class StoryReferenceIn(BaseModel):
    index: int
    url: str
    analysis: Optional[Dict[str, Any]] = None


class StoryPlanRequest(BaseModel):
    prompt: str
    duration: int  # total seconds, 20–60
    aspect_ratio: Optional[str] = "16:9"
    # Analysed reference images (characters/objects/backgrounds/styles) the
    # scenes must stay faithful to.
    references: Optional[List[StoryReferenceIn]] = None
    # Optional target number of scenes (from a Brief re-plan where the user
    # set an explicit scene count). Clamped to what the duration allows; None
    # lets the planner decide.
    scenes: Optional[int] = None
    # Optional concept/story guidance (from a Brief re-plan where the user
    # edited the concept). When present, the planner follows this direction
    # instead of inventing a fresh story.
    story: Optional[str] = None
    # User-picked writer LLM: "claude_opus" | "claude_sonnet" | "gpt" | "gemini".
    llm: Optional[str] = None


def _distribute(total: int, n: int) -> list[int]:
    base, rem = divmod(total, n)
    return [base + (1 if i < rem else 0) for i in range(n)]


def _scene_ref_indices(raw_refs: Any, valid: set[int]) -> list[int]:
    out: list[int] = []
    for r in raw_refs if isinstance(raw_refs, list) else []:
        try:
            idx = int(r)
        except (TypeError, ValueError):
            continue
        if idx in valid and idx not in out:
            out.append(idx)
    return out


def _normalize_scenes(
    raw: Any,
    total: int,
    valid_ref_indices: Optional[set[int]] = None,
    target_n: Optional[int] = None,
) -> list[dict]:
    """Coerce the LLM's scenes into clip-able ones: integer durations within
    the providers' limits that sum EXACTLY to `total` (the whole feature's
    contract), fixing count and pacing as gently as possible. When `target_n`
    is given (a user-requested scene count from a Brief re-plan), the scene
    list is trimmed/extended to exactly that many (clamped to feasible)."""
    valid_refs = valid_ref_indices or set()
    scenes = [
        {
            "title": str(s.get("title") or f"Scene {i + 1}").strip(),
            "duration": s.get("duration"),
            "image_prompt": str(s.get("image_prompt") or "").strip(),
            "references": _scene_ref_indices(s.get("references"), valid_refs),
        }
        for i, s in enumerate(raw if isinstance(raw, list) else [])
        if isinstance(s, dict) and str(s.get("image_prompt") or "").strip()
    ]
    if not scenes:
        raise HTTPException(status_code=502, detail="The LLM returned no usable scenes")

    # References were supplied but the LLM assigned none anywhere — the
    # feature's contract is "generate from the user's references", so fall
    # back to using every reference in every scene.
    if valid_refs and not any(s["references"] for s in scenes):
        all_refs = sorted(valid_refs)
        for s in scenes:
            s["references"] = list(all_refs)

    # Too many scenes → merge the tail; too few → continue the last scene, so
    # every scene stays within the per-clip ceiling.
    max_n = max(1, total // _SCENE_MIN)
    scenes = scenes[:max_n]
    min_n = -(-total // _HARD_SCENE_MAX)  # ceil
    while len(scenes) < min_n:
        last = scenes[-1]
        scenes.append({**last, "title": f"{last['title']} (cont.)"})

    # Honour a user-requested scene count, clamped to what the duration can
    # actually hold (min_n…max_n).
    if target_n:
        want = min(max(int(target_n), min_n), max_n)
        scenes = scenes[:want]
        while len(scenes) < want:
            last = scenes[-1]
            scenes.append({**last, "title": f"{last['title']} (cont.)"})

    durations: list[int] = []
    for s in scenes:
        try:
            d = int(round(float(s["duration"])))
        except (TypeError, ValueError):
            d = 0
        durations.append(min(max(d, _SCENE_MIN), _HARD_SCENE_MAX))

    # Nudge toward the exact total while respecting bounds; if the plan is too
    # far off to fix that way, fall back to an even split (always valid given
    # min_n/max_n above).
    guard = 0
    while sum(durations) != total and guard < 200:
        guard += 1
        diff = total - sum(durations)
        if diff > 0:
            i = min(range(len(durations)), key=lambda k: durations[k])
            if durations[i] >= _HARD_SCENE_MAX:
                break
            durations[i] += 1
        else:
            i = max(range(len(durations)), key=lambda k: durations[k])
            if durations[i] <= _SCENE_MIN:
                break
            durations[i] -= 1
    if sum(durations) != total:
        durations = _distribute(total, len(scenes))

    return [
        {
            "index": i,
            "title": s["title"],
            "duration": durations[i],
            "image_prompt": s["image_prompt"],
            "reference_indices": s["references"],
        }
        for i, s in enumerate(scenes)
    ]


@router.post("/story/plan", dependencies=[require_permission("resources:write")])
async def plan_story(
    body: StoryPlanRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    idea = (body.prompt or "").strip()
    if not idea:
        raise HTTPException(status_code=400, detail="prompt is required")
    total = int(body.duration or 0)
    if not (_TOTAL_MIN <= total <= _TOTAL_MAX):
        raise HTTPException(
            status_code=400,
            detail=f"duration must be between {_TOTAL_MIN} and {_TOTAL_MAX} seconds",
        )

    # Analysed reference images: the cast/set the scenes must stay faithful to.
    references = [
        r for r in (body.references or [])
        if (r.url or "").strip() and isinstance(r.analysis, dict)
    ]
    ref_by_index = {r.index: r for r in references}
    # [style] references (palette/typography/motion feel) inform the bible's
    # grading/camera as TEXT — they're never a literal object to place in a
    # scene, so they're excluded from what a scene can "cast" regardless of
    # what the planning LLM outputs (_PLAN_REFS_RULES tells it the same, but
    # this is the structural backstop, not just an instruction to follow).
    castable_ref_indices = {i for i, r in ref_by_index.items() if (r.analysis or {}).get("kind") != "style"}

    min_n = -(-total // _SCENE_MAX)
    max_n = total // _SCENE_MIN
    # A user-requested scene count (Brief re-plan), clamped to feasible.
    feasible_min = -(-total // _HARD_SCENE_MAX)
    feasible_max = max(1, total // _SCENE_MIN)
    target_n = None
    if body.scenes:
        target_n = min(max(int(body.scenes), feasible_min), feasible_max)
    user = (
        f"Idea:\n{idea}\n\n"
        f"Total duration: exactly {total} seconds.\n"
        f"Aspect ratio: {body.aspect_ratio or '16:9'}.\n"
    )
    if target_n:
        user += f"Use EXACTLY {target_n} scenes ({_SCENE_MIN}–{_HARD_SCENE_MAX}s each, summing to {total})."
    else:
        user += f"Use between {min_n} and {max_n} scenes ({_SCENE_MIN}–{_SCENE_MAX}s each, summing to {total})."
    # Concept guidance from a Brief edit — the planner follows it rather than
    # inventing a fresh story.
    guidance = (body.story or "").strip()
    if guidance:
        user += f"\n\nFollow this concept/story direction closely:\n{guidance}"
    system = _PLAN_SYSTEM
    if references:
        system = _PLAN_SYSTEM + "\n" + _PLAN_REFS_RULES
        ref_lines = []
        for r in references:
            a = r.analysis or {}
            ref_lines.append(
                f"{r.index}. [{a.get('kind', 'other')}] \"{a.get('name', 'reference')}\": {a.get('description', '')}"
            )
        user += "\n\nReference images:\n" + "\n".join(ref_lines)

    # Runs as a background task (mirrors /story/merge's pattern) rather than
    # being awaited inline: this is the only LLM call on the critical path
    # that has NOTHING durable behind it if the caller disconnects (a page
    # refresh kills the in-flight browser fetch) — the result would otherwise
    # be lost forever with the session stuck showing "planning". Stashing the
    # raw result on an Item keyed by generation_id lets a still-connected
    # frontend pick it up the same way scene/merge generations already do
    # (SSE + the reliability-net poll), and a disconnected one recover it via
    # the same /story/generation/{id} lookup once it reconnects/reloads.
    org_id = ctx.organization_id
    generation_id = str(uuid.uuid4())
    bind_user_id(ctx.user_id)

    async def _bg():
        async with standalone_background_session(ctx) as db:
            doc = await create_initial_item(
                db,
                organization_id=org_id, user_id=ctx.user_id,
                type="story_plan", model_name=body.llm or "gpt",
                prompt=idea, params={}, generation_id=generation_id,
            )
            record_id = doc["id"]
            await broadcast_event(
                org_id, "started",
                {**doc, "project_id": None, "generation_id": generation_id},
                record_id, None, ctx.user_id,
            )
            try:
                data = await _llm_json(ctx, system, user, body.llm)
                scenes = _normalize_scenes(
                    data.get("scenes"), total, valid_ref_indices=castable_ref_indices, target_n=target_n
                )
                # Resolve each scene's reference numbers to the actual image
                # URLs the image-generation step will attach.
                for s in scenes:
                    s["reference_urls"] = [ref_by_index[i].url for i in s["reference_indices"]]
                result = {
                    "status": "success",
                    # Short display title (2–5 words) for narrow UI labels.
                    "title": str(data.get("title") or "").strip(),
                    "story": str(data.get("story") or "").strip(),
                    # Reference-sheet prompt for the optional master reference
                    # image (used when the frontend attached no references).
                    "master_prompt": str(data.get("master_prompt") or "").strip(),
                    # The film's locked production design — appended to every
                    # generation prompt for consistency.
                    "bible": _normalize_bible(data.get("bible")),
                    "total_duration": total,
                    "scenes": scenes,
                    "references": [
                        {"index": r.index, "url": r.url, "analysis": r.analysis} for r in references
                    ],
                }
                await set_item_fields(db, record_id, {"gen_params": result})
                final = await update_item_success(db, record_id, url="story-plan")
                await broadcast_event(org_id, "completed", final, record_id, None, ctx.user_id)
            except Exception as e:  # noqa: BLE001 — surfaced on the item itself
                logger.exception("❌ Story plan failed")
                failed = await update_item_failed(db, record_id, str(e))
                await broadcast_event(org_id, "failed", failed, record_id, None, ctx.user_id)

    asyncio.create_task(_bg())
    return {
        "status": "pending",
        "generation_id": generation_id,
        "message": "Planning started. Poll /story/generation/{generation_id} for the result.",
    }


# --- Step 2: per-scene image-to-video motion prompts --------------------------

_VIDEO_PROMPT_SYSTEM = """You write motion prompts for image-to-video AI models (Kling, Seedance).
Each scene of a short film already has a generated start frame; your prompt animates it.

Return ONLY a JSON object of this exact shape:
{"scenes": [{"index": <int>, "video_prompt": "..."}]}

Rules:
- Write one video_prompt per input scene, keyed by the scene's index.
- Describe motion and change over time: the subject's action, camera movement (push-in, pan, dolly, handheld…), pacing that fits the scene's duration, atmosphere and sound cues.
- The start frame already fixes the scene's appearance — do not re-describe it in detail; focus on what MOVES.
- Keep continuity between consecutive scenes so the clips cut together as one film.
- Never ask for on-screen text of any kind: no titles, captions, subtitles, words, letters or logos appearing in the video (AI models render text misspelled and blurry).
- Write in English."""

# Keyframe bridging: every clip (except the last) is ALSO given the next
# scene's start frame as its END frame, so the motion must arrive there.
_VIDEO_PROMPT_BRIDGE_RULE = """
- IMPORTANT: each clip is generated with the NEXT scene's opening frame as its ending keyframe. Choreograph the motion so the shot naturally ARRIVES at the next scene's composition by its end (the last scene simply resolves its own action). Describe the journey between the two frames, not a static loop."""

# Cinematic mode, Kling: Kling has a NATIVE multi-prompt syntax (pipe-separated
# segments it paces automatically across the clip) — the same mechanism the
# panel's manual "Custom Multishot" editor already drives.
_VIDEO_PROMPT_CINEMATIC_KLING_RULE = """

- CINEMATIC MODE (Kling native multi-shot): write this scene's video_prompt in Kling's own pipe-separated multi-prompt format: one overall sentence for the scene, then " | ", then 2–4 shot segments — each ALSO separated by " | " — describing ONE distinct camera setup apiece. Shape: "a young man walks down a rainy neon street | wide establishing shot from behind, slow tracking forward | medium side-tracking shot alongside him | close-up on his face, shallow depth of field".
- Kling paces each pipe-segment across the clip's duration automatically — do NOT write timestamps.
- Vary shot size (wide / medium / close-up / extreme close-up), angle (eye-level / low-angle / high-angle / over-the-shoulder) and movement (static / push-in / tracking / dolly / pan / tilt) across the segments so the sequence reads like a professional director's shot list, not one continuous take.
- Keep the subject, wardrobe, environment, weather and lighting IDENTICAL across every segment — only the camera changes.
- Fold a few cinematography style keywords (e.g. cinematic realism, shallow depth of field, natural motion blur, volumetric lighting, 35mm film look) into the LAST segment rather than adding them as a separate pipe segment."""

# Cinematic mode, everyone else (Seedance, …): no native multi-shot syntax, so
# the shot list is spelled out as prose with explicit timestamps.
_VIDEO_PROMPT_CINEMATIC_GENERIC_RULE = """

- CINEMATIC MODE: write this scene's video_prompt as ONE prompt structured like a professional shot list, in this exact shape:
  1. One opening sentence: "Maintain the same character, clothing, hairstyle, facial features, lighting, weather, and environment throughout." (adapt the subject description to this scene).
  2. Then, on new lines, break THIS SCENE's own duration (given with each scene below) into 2–4 sequential shots, back-to-back, whose time ranges sum EXACTLY to that duration, each formatted as "Shot N (start–ends): description" with whole-second boundaries — e.g. for a 9s scene: "Shot 1 (0–3s): ...", "Shot 2 (3–6s): ...", "Shot 3 (6–9s): ...". Use fewer, longer shots for short scenes and more for long ones.
  3. Each shot names ONE clear camera setup (shot size, angle, movement — wide establishing / medium tracking / close-up / low-angle / over-the-shoulder / dolly / tilt / pan) and what happens in it; vary these across shots like a director's shot list.
  4. End with one closing line of cinematography style keywords: cinematic realism, smooth camera transitions, realistic motion, shallow depth of field, natural motion blur, volumetric lighting, high detail."""


def _supports_end_frame(video_model: str) -> bool:
    """Mirrors the frontend's supportsEndFrame — Kling and Seedance take a
    start+end frame pair; everything else (LTX, …) takes a single image."""
    return video_model.startswith("kling") or video_model == "seedance_2_0"


# Models whose provider call accepts a native `generate_audio` flag (mirrors
# fal_helper._DEFAULT_PAYLOADS' `generate_audio` keys) — these generate sound
# straight from the same prompt text driving the visuals. LTX has no native
# audio generation at all, so describing sound for it would be inert.
_AUDIO_CAPABLE_VIDEO_MODELS = {"kling_3_0_pro", "kling_3_0_standard", "kling_o3_pro", "seedance_2_0"}

_VIDEO_PROMPT_AUDIO_GENERATED_RULE = """
- AUDIO: this clip renders audio generated by the model directly from this prompt's wording — describe what should be HEARD as part of the scene (ambient sound, foley, distinct sound effects, brief dialogue/vocalizations if a character speaks, mood-appropriate score or music cues), woven into the same sentence(s) describing the visual action rather than listed separately."""

_VIDEO_PROMPT_AUDIO_SILENT_RULE = """
- AUDIO: this clip renders with NO audio track — do not describe any sound, dialogue, music or sound effect; keep the prompt purely visual."""


class ScenePromptIn(BaseModel):
    index: int
    title: Optional[str] = ""
    duration: int
    image_prompt: str


class VideoPromptsRequest(BaseModel):
    prompt: Optional[str] = ""
    story: str
    # "bridge" (start→next-start keyframe bridging), "cinematic" (multi-angle
    # shot list within each clip, still bridged when the model supports it),
    # or "independent" (plain single-motion clips).
    continuity: Optional[str] = None
    # The video model the scenes will be generated with — picks the cinematic
    # prompt format (Kling's native pipe multi-prompt vs. a generic
    # timestamped shot list for everyone else).
    video_model: Optional[str] = None
    # "generated" (model-native ambience/sound/dialogue) or "silent" — decides
    # whether motion prompts describe audio cues at all, since audio-capable
    # models generate sound FROM the same prompt text driving the visuals.
    audio: Optional[str] = None
    # The plan's locked production design; motion prompts must respect it.
    bible: Optional[Dict[str, Any]] = None
    scenes: List[ScenePromptIn]
    # User-picked writer LLM: "claude_opus" | "claude_sonnet" | "gpt" | "gemini".
    llm: Optional[str] = None


@router.post("/story/video-prompts", dependencies=[require_permission("resources:write")])
async def story_video_prompts(
    body: VideoPromptsRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    if not body.scenes:
        raise HTTPException(status_code=400, detail="scenes are required")
    continuity = (body.continuity or "").strip()
    video_model = (body.video_model or "").strip()
    # Cinematic clips are ALSO bridged (start+end frame) whenever the model
    # supports it — multi-angle choreography and seamless cuts are additive,
    # not alternatives.
    will_bridge = continuity in ("bridge", "cinematic") and _supports_end_frame(video_model)
    system = _VIDEO_PROMPT_SYSTEM
    if will_bridge:
        system += _VIDEO_PROMPT_BRIDGE_RULE
    if continuity == "cinematic":
        system += (
            _VIDEO_PROMPT_CINEMATIC_KLING_RULE
            if video_model.startswith("kling")
            else _VIDEO_PROMPT_CINEMATIC_GENERIC_RULE
        )
    # Only tell the model to WRITE audio cues when this video model can
    # actually RENDER audio from them — otherwise the instruction would just
    # add inert text (see _AUDIO_CAPABLE_VIDEO_MODELS).
    audio = (body.audio or "generated").strip().lower()
    if audio == "silent":
        system += _VIDEO_PROMPT_AUDIO_SILENT_RULE
    elif video_model in _AUDIO_CAPABLE_VIDEO_MODELS:
        system += _VIDEO_PROMPT_AUDIO_GENERATED_RULE
    bible = _normalize_bible(body.bible)
    if bible:
        system += (
            "\n- Respect the LOCKED production design below in every shot — the lens, "
            "camera height, movement style, lighting and grade never change between "
            "shots unless a scene explicitly demands it."
        )
    lines = [
        f"Scene {s.index} — \"{s.title or ''}\" ({s.duration}s): {s.image_prompt}"
        for s in body.scenes
    ]
    user = (
        (f"Original idea:\n{body.prompt}\n\n" if (body.prompt or "").strip() else "")
        + f"Story:\n{body.story}\n\n"
        + (
            "Locked production design:\n"
            + "\n".join(f"- {k}: {v}" for k, v in bible.items())
            + "\n\n"
            if bible
            else ""
        )
        + "Scenes:\n" + "\n".join(lines)
    )
    data = await _llm_json(ctx, system, user, body.llm)
    by_index: dict[int, str] = {}
    for s in data.get("scenes") or []:
        if not isinstance(s, dict):
            continue
        vp = str(s.get("video_prompt") or "").strip()
        try:
            idx = int(s.get("index"))
        except (TypeError, ValueError):
            continue
        if vp:
            by_index[idx] = vp
    return {
        "status": "success",
        "scenes": [
            {
                "index": s.index,
                # Fall back to animating the image prompt when the LLM skipped one.
                "video_prompt": by_index.get(s.index)
                or f"{s.image_prompt} — cinematic camera movement, natural motion",
            }
            for s in body.scenes
        ],
    }


# --- Step 3: merge the per-scene clips with ffmpeg ----------------------------

class StoryMergeRequest(BaseModel):
    # Scene clip URLs, already in scene order.
    video_urls: List[str]
    prompt: Optional[str] = ""
    project_id: Optional[str] = None
    key_frame_id: Optional[str] = None
    aspect_ratio: Optional[str] = "16:9"
    resolution: Optional[str] = "1080p"
    duration: Optional[str] = None  # total, e.g. "30" or "30s" (the PLANNED total — see total_seconds below for why this is only ever a fallback)
    # Scene metadata (prompts/durations) kept on the item for provenance.
    scenes: Optional[List[Dict[str, Any]]] = None
    # "generated" (model-native, already baked into the scene clips — nothing
    # more to do here) / "silent" / "music" / "voiceover_music". Only the
    # latter two need anything from this endpoint, since scene clips for them
    # were generated audio-less.
    audio_mode: Optional[str] = None
    music_prompt: Optional[str] = None
    # The story synopsis — source material for auto-written narration when
    # narration_text is blank (the user never typed their own script). Kept
    # separate from narration_text (rather than the frontend pre-resolving
    # the fallback itself) specifically so the backend can size the
    # auto-written narration to the ACTUAL merged runtime below, which can
    # now differ freely from whatever was originally planned once scenes are
    # added/removed/reordered on Animate.
    story: Optional[str] = None
    narration_text: Optional[str] = None
    narration_voice_id: Optional[str] = None
    # ISO 639-1 code ("en"/"ko") forcing ElevenLabs' pronunciation/accent —
    # None falls back to its own language auto-detection.
    narration_language: Optional[str] = None
    # Which LLM writes the auto narration script (same picker as planning/
    # motion prompts) — None falls back through every configured provider.
    llm: Optional[str] = None
    # "voiceover_music" only: burn captions timed from the narration's word
    # alignment via ffmpeg drawtext.
    captions_enabled: Optional[bool] = None


def _local_media_dir() -> Path:
    # backend/api/routes/story_video.py → plugin root is three levels up.
    return Path(__file__).resolve().parents[3] / ".palette" / "story-media"


_MEDIA_CONTENT_TYPES = {
    "mp4": "video/mp4",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
}


async def _store_media(ctx: PluginContext, data: bytes, content_type: str, ext: str) -> str:
    """Upload media bytes to app storage. Local dev storage hands back
    file:// URLs that browsers refuse — there the bytes are kept in a local
    cache served by GET /story/media/{name} instead. Shared by the merged
    video AND the scene-media endpoint (image/video uploads, thumbnails)."""
    ext = ext.lstrip(".").lower() or "mp4"
    key = f"story_board_video/outputs/videos/{uuid.uuid4()}.{ext}"
    name = key.rsplit("/", 1)[-1]
    saved = await ctx.storage.upload_file(name, data, content_type, key=key)
    url = saved.get("file_url") or saved.get("fileUrl") or saved.get("url")
    if isinstance(url, str) and not url.startswith("file://"):
        return url
    cache = _local_media_dir()
    cache.mkdir(parents=True, exist_ok=True)
    (cache / name).write_bytes(data)
    logger.info("📁 Local dev storage: serving %s via /story/media/%s", content_type, name)
    return f"{_PLUGIN_BASE}/story/media/{name}"


async def _store_merged(ctx: PluginContext, data: bytes) -> str:
    return await _store_media(ctx, data, "video/mp4", "mp4")


_MEDIA_NAME_RE = re.compile(r"^[a-f0-9-]{36}\.(mp4|jpg|jpeg|png|webp)$")


@router.get("/story/media/{name}", dependencies=[require_permission("resources:read")])
async def story_media(name: str):
    """Serves locally-cached merged videos / scene media (dev-storage
    fallback only)."""
    if not _MEDIA_NAME_RE.match(name):
        raise HTTPException(status_code=404, detail="Not found")
    path = _local_media_dir() / name
    if not path.is_file():
        raise HTTPException(status_code=404, detail="Not found")
    ext = name.rsplit(".", 1)[-1].lower()
    return FileResponse(path, media_type=_MEDIA_CONTENT_TYPES.get(ext, "application/octet-stream"))


_SCENE_MEDIA_MAX_BYTES = 30 * 1024 * 1024  # 30 MB — matches /assets/reference's cap.


@router.post("/story/scene-media", dependencies=[require_permission("resources:write")])
async def upload_scene_media(
    file: UploadFile = File(...),
    duration: float = Form(5.0),
    aspect_ratio: str = Form("16:9"),
    resolution: str = Form("1080p"),
    ctx: PluginContext = Depends(get_ctx),
):
    """Turns a directly-uploaded image or video into a ready-to-merge scene —
    Animate's "add a scene" for something the user supplies themselves (e.g.
    a closing "thank you" card) rather than generating through the AI
    pipeline. An image is looped into a short silent(-audio-track) clip of
    `duration` seconds; a video is used as-is, with its real duration
    measured and a poster frame extracted. Both come back normalized to the
    run's aspect ratio/resolution so they concatenate cleanly with every
    other scene regardless of where in the timeline the user places it."""
    data = await file.read()
    if not data:
        raise HTTPException(status_code=400, detail="Empty file")
    if len(data) > _SCENE_MEDIA_MAX_BYTES:
        raise HTTPException(status_code=413, detail="File too large (max 30MB)")

    content_type = (file.content_type or "").lower()
    is_video = content_type.startswith("video/")
    is_image = content_type.startswith("image/")
    if not is_video and not is_image:
        raise HTTPException(status_code=400, detail="Only image or video files are supported")

    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        raise HTTPException(
            status_code=503,
            detail=f"ffmpeg is not available in this environment: {ffmpeg_unavailable_reason()}",
        )

    suffix = (Path(file.filename or "").suffix or (".mp4" if is_video else ".jpg")).lower()
    with tempfile.TemporaryDirectory(prefix="story-scene-media-") as tmp:
        src_path = os.path.join(tmp, f"src{suffix}")
        Path(src_path).write_bytes(data)
        width, height = dimensions_for(aspect_ratio, resolution)

        if is_image:
            clip_duration = max(1.0, min(30.0, duration))
            out_path = os.path.join(tmp, "clip.mp4")
            await anyio.to_thread.run_sync(
                functools.partial(image_to_video, ffmpeg, src_path, out_path, width, height, clip_duration)
            )
            video_url = await _store_media(ctx, Path(out_path).read_bytes(), "video/mp4", "mp4")
            image_url = await _store_media(
                ctx, data, content_type or "image/jpeg", suffix.lstrip(".") or "jpg"
            )
            return {
                "status": "success",
                "image_url": image_url,
                "video_url": video_url,
                "duration": clip_duration,
            }

        # Video upload: measure its real duration on the ORIGINAL file first
        # (re-encoding can shift the container's reported duration slightly),
        # then re-encode to fill the run's WxH exactly — cropping whatever
        # doesn't fit rather than leaving it at its own aspect ratio, same
        # treatment an uploaded image gets in image_to_video above.
        real_duration = (
            await anyio.to_thread.run_sync(functools.partial(probe_duration, ffmpeg, src_path))
        ) or duration
        reencoded_path = os.path.join(tmp, "reencoded.mp4")
        await anyio.to_thread.run_sync(
            functools.partial(reencode_scene_video, ffmpeg, src_path, reencoded_path, width, height)
        )

        image_url: Optional[str] = None
        try:
            thumb_path = os.path.join(tmp, "thumb.jpg")
            await anyio.to_thread.run_sync(
                functools.partial(extract_first_frame, ffmpeg, reencoded_path, thumb_path)
            )
            image_url = await _store_media(ctx, Path(thumb_path).read_bytes(), "image/jpeg", "jpg")
        except Exception as e:  # noqa: BLE001 — cosmetic only, the video itself still ships
            logger.warning("Scene video poster extraction failed: %s", e)

        video_url = await _store_media(ctx, Path(reencoded_path).read_bytes(), "video/mp4", "mp4")
        return {
            "status": "success",
            "image_url": image_url,
            "video_url": video_url,
            "duration": round(real_duration, 2),
        }


_NARRATION_SYSTEM = """You write a short spoken narration script for a video, sized to fit naturally within a given time budget.

Return ONLY a JSON object of this exact shape: {"narration": "..."}

Rules:
- Plain spoken prose — no stage directions, headings, or on-screen text cues.
- Written in the same language the story is described in.
- Must comfortably fit within the given time budget at a natural speaking pace — stay at or under the given word limit.
- Cover the story's actual arc; don't pad, repeat ideas, or trail off just to fill time."""


async def _write_fitted_narration(
    ctx: PluginContext, story: str, target_seconds: float, llm: Optional[str]
) -> str:
    """Auto-narration (no user-authored script) is written HERE, sized to
    the ACTUAL merged video's runtime, rather than just reading the story
    synopsis verbatim regardless of how long the video actually is — which
    can now diverge freely from what was originally planned once scenes are
    added/removed/reordered on Animate, at planning time nobody could size
    a fixed synopsis for. Falls back to the raw synopsis on any failure (no
    LLM configured, bad response, …) — the merge still ships either way."""
    story = (story or "").strip()
    if not story:
        return ""
    buffer_seconds = min(max(target_seconds * 0.08, 1.0), 2.5)
    target = max(3.0, target_seconds - buffer_seconds)
    max_words = max(8, int(target * 2.3))  # ~2.3 words/sec average speaking pace
    user_text = (
        f"Story: {story}\n\n"
        f"Write a natural spoken narration of this story.\n"
        f"Requirements:\n"
        f"- Maximum {max_words} words.\n"
        f"- Must comfortably fit within {target:.1f} seconds of speech.\n"
        f"- Finish naturally before the video ends — do not pad or repeat ideas."
    )
    try:
        data = await _llm_json(ctx, _NARRATION_SYSTEM, user_text, llm)
        narration = str(data.get("narration") or "").strip()
        return narration or story
    except Exception as e:  # noqa: BLE001 — the plain story synopsis still works as narration
        logger.warning("Auto-narration write failed, falling back to the story synopsis: %s", e)
        return story


@router.post("/story/merge", dependencies=[require_permission("resources:write")])
async def run_story_merge(
    request: StoryMergeRequest,
    ctx: PluginContext = Depends(get_ctx),
):
    org_id = ctx.organization_id
    bind_user_id(ctx.user_id)

    urls = [str(u).strip() for u in (request.video_urls or []) if u and str(u).strip()]
    if len(urls) < 2:
        raise HTTPException(status_code=400, detail="At least two scene videos are required")

    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        raise HTTPException(
            status_code=503,
            detail=(
                "ffmpeg is not available in this environment, cannot merge scene "
                f"clips: {ffmpeg_unavailable_reason()}"
            ),
        )

    if request.project_id:
        project = await get_project(ctx.db, ctx.user_id, request.project_id)
        if not project:
            raise HTTPException(status_code=404, detail="Project not found")
        if not request.key_frame_id:
            raise HTTPException(status_code=400, detail="key_frame_id is required")
        kf = await get_key_frame(ctx.db, ctx.user_id, request.project_id, request.key_frame_id)
        if kf is None:
            raise HTTPException(status_code=404, detail="Key frame not found")
        project_id = request.project_id
        key_frame_id = kf["id"]
    else:
        project_id = str(uuid.uuid4())
        key_frame_id = None

    generation_id = str(uuid.uuid4())
    merged_params: dict = {
        "aspect_ratio": request.aspect_ratio or "16:9",
        "resolution": request.resolution or "1080p",
        "source": "story",
        "scene_count": len(urls),
    }
    if request.duration:
        merged_params["duration"] = request.duration.rstrip("sS").strip() or request.duration
    if request.scenes:
        merged_params["scenes"] = request.scenes

    # The bg task mirrors /generate/video's contract: create the item, then
    # started → processing (download/merge logs) → completed/failed over SSE.
    async def _bg():
        async with standalone_background_session(ctx) as db:
            doc = await create_initial_item(
                db,
                organization_id=ctx.organization_id, user_id=ctx.user_id,
                type="video", model_name=LONG_VIDEO_MODEL,
                prompt=request.prompt or "", params=merged_params,
                project_id=project_id, key_frame_id=key_frame_id,
                generation_id=generation_id,
            )
            record_id = doc["id"]
            await broadcast_event(
                org_id, "started",
                {**doc, "project_id": project_id, "generation_id": generation_id},
                record_id, project_id, ctx.user_id,
            )

            async def _progress(message: str):
                await broadcast_event(
                    org_id, "processing",
                    {
                        "id": record_id,
                        "model_name": LONG_VIDEO_MODEL,
                        "project_id": project_id,
                        "generation_id": generation_id,
                        "key_frame_id": key_frame_id,
                        "status": "processing",
                        "prompt": request.prompt,
                        "aspect_ratio": merged_params.get("aspect_ratio"),
                        "duration": merged_params.get("duration"),
                        "logs": [message],
                    },
                    record_id, project_id, ctx.user_id,
                )

            try:
                with tempfile.TemporaryDirectory(prefix="story-merge-") as tmp:
                    paths: list[str] = []
                    async with httpx.AsyncClient(timeout=300, follow_redirects=True) as client:
                        for i, u in enumerate(urls):
                            await _progress(f"Downloading scene {i + 1}/{len(urls)}…")
                            path = os.path.join(tmp, f"clip_{i:03d}.mp4")
                            if u.startswith("file://"):
                                # Local dev storage clip — copy straight from disk.
                                shutil.copyfile(unquote(urlparse(u).path), path)
                            else:
                                resp = await client.get(u)
                                resp.raise_for_status()
                                with open(path, "wb") as f:
                                    f.write(resp.content)
                            paths.append(path)

                    await _progress(f"Merging {len(paths)} scenes with ffmpeg…")
                    width, height = dimensions_for(
                        merged_params.get("aspect_ratio"), merged_params.get("resolution")
                    )
                    out_path = os.path.join(tmp, "merged.mp4")
                    await anyio.to_thread.run_sync(
                        functools.partial(
                            merge_videos, ffmpeg, paths, out_path, width, height
                        )
                    )

                    # Generated-audio modes: the scene clips themselves were
                    # rendered audio-less (see /generate/video's audio flag),
                    # so `out_path` here is a silent concat — layer narration/
                    # music (ElevenLabs) and captions (ffmpeg drawtext) on top.
                    audio_mode = (request.audio_mode or "").strip().lower()
                    # Narration is wanted whenever voiceover_music is picked,
                    # whether the user typed their own script or not — a
                    # blank narration_text auto-writes one from the story
                    # synopsis below, sized to the real merged runtime.
                    wants_narration = audio_mode == "voiceover_music" and bool(
                        (request.narration_text or "").strip() or (request.story or "").strip()
                    )
                    # voiceover_music ALWAYS wants background music (falls
                    # back to a plain ambient prompt below if the user didn't
                    # write one) — a plain "music" pick still needs an
                    # actual prompt, since there narration isn't filling the
                    # silence if the user left this blank too.
                    wants_music = audio_mode == "voiceover_music" or (
                        audio_mode == "music" and bool((request.music_prompt or "").strip())
                    )
                    wants_captions = wants_narration and bool(request.captions_enabled)
                    if wants_narration or wants_music:
                        eleven_key = read_secret(ctx, "ELEVEN_API_KEY")
                        if not eleven_key:
                            await _progress("ELEVEN_API_KEY is not configured — skipping generated audio.")
                        else:
                            # The concat's REAL runtime, not the planned sum
                            # of scene durations — provider clips routinely
                            # land a little short/long of what was
                            # requested, and pinning the audio budget to the
                            # plan instead of reality is exactly what let
                            # narration run past the actual video before (or
                            # end noticeably early).
                            total_seconds = await anyio.to_thread.run_sync(
                                functools.partial(probe_duration, ffmpeg, out_path)
                            )
                            if not total_seconds:
                                total_seconds = float(merged_params.get("duration") or 0) or sum(
                                    float(s.get("duration") or 0) for s in (request.scenes or [])
                                ) or 30.0
                            narration_path: Optional[str] = None
                            music_path: Optional[str] = None
                            captions: Optional[list] = None
                            narration_rate = 1.0

                            # Narration and music are generated by two
                            # separate ElevenLabs APIs (TTS vs. Music) that
                            # can fail independently (access, rate limits,
                            # content policy). Each gets its OWN try/except
                            # so one failing never silently throws away an
                            # already-successful other track — previously
                            # both lived in one shared try block, so a
                            # music-generation error discarded a perfectly
                            # good narration too (and vice versa).
                            if wants_narration:
                                try:
                                    narration_source = (request.narration_text or "").strip()
                                    if not narration_source:
                                        await _progress("Writing narration for this video's length…")
                                        narration_source = await _write_fitted_narration(
                                            ctx, request.story or "", total_seconds, request.llm
                                        )
                                    await _progress("Generating narration…")
                                    voice_id = (
                                        (request.narration_voice_id or "").strip()
                                        or elevenlabs_helper.DEFAULT_VOICE_ID
                                    )
                                    narration_bytes, words = await elevenlabs_helper.generate_narration(
                                        eleven_key,
                                        narration_source,
                                        voice_id,
                                        (request.narration_language or "").strip() or None,
                                    )
                                    narration_path = os.path.join(tmp, "narration.mp3")
                                    Path(narration_path).write_bytes(narration_bytes)
                                    # Narration is free-typed by the user (no
                                    # word-budget applied before TTS), so it
                                    # can easily run longer than the video.
                                    # Reserve a small tail buffer and, if the
                                    # narration overshoots that budget, speed
                                    # it up moderately (capped so it never
                                    # sounds rushed) instead of letting the
                                    # final `-t` trim below chop it off
                                    # mid-sentence.
                                    narration_seconds = (words[-1].get("end") or 0.0) if words else 0.0
                                    buffer_seconds = min(max(total_seconds * 0.08, 0.5), 2.0)
                                    target_seconds = max(1.0, total_seconds - buffer_seconds)
                                    if narration_seconds > target_seconds:
                                        narration_rate = min(1.15, narration_seconds / target_seconds)
                                    if wants_captions:
                                        captions = elevenlabs_helper.group_captions(words)
                                        if narration_rate != 1.0:
                                            captions = [
                                                {
                                                    **c,
                                                    "start": (c["start"] or 0.0) / narration_rate,
                                                    "end": (c["end"] or 0.0) / narration_rate,
                                                }
                                                for c in captions
                                            ]
                                except Exception as narration_err:  # noqa: BLE001 — music/mux still proceed
                                    logger.warning("⚠️ Story narration generation failed: %s", narration_err)
                                    await _progress(
                                        f"Narration generation failed ({narration_err}); continuing without it."
                                    )
                                    narration_path = None
                                    captions = None
                                    narration_rate = 1.0

                            if wants_music:
                                try:
                                    await _progress("Generating music…")
                                    music_source = (request.music_prompt or "").strip()
                                    if not music_source:
                                        # voiceover_music with no music prompt
                                        # typed — still wants background
                                        # music, just with a sensible default
                                        # rather than nothing at all.
                                        music_source = (
                                            "Soft, understated ambient background music for a narrated "
                                            "video — gentle, unobtrusive, no vocals, no lyrics, no sudden "
                                            "dynamic swings that would compete with spoken narration."
                                        )
                                    music_bytes = await elevenlabs_helper.generate_music(
                                        eleven_key, music_source, int(total_seconds * 1000)
                                    )
                                    music_path = os.path.join(tmp, "music.mp3")
                                    Path(music_path).write_bytes(music_bytes)
                                except Exception as music_err:  # noqa: BLE001 — narration/mux still proceed
                                    logger.warning("⚠️ Story music generation failed: %s", music_err)
                                    await _progress(
                                        f"Music generation failed ({music_err}); continuing without it."
                                    )
                                    music_path = None

                            if narration_path or music_path or captions:
                                try:
                                    await _progress("Mixing generated audio into the final video…")
                                    mixed_path = os.path.join(tmp, "mixed.mp4")
                                    await anyio.to_thread.run_sync(
                                        functools.partial(
                                            mux_final_audio, ffmpeg, out_path, mixed_path, total_seconds,
                                            narration_path=narration_path, music_path=music_path,
                                            captions=captions, narration_rate=narration_rate,
                                        )
                                    )
                                    out_path = mixed_path
                                except Exception as mux_err:  # noqa: BLE001 — the plain merged video still ships
                                    logger.warning("⚠️ Story audio mux failed: %s", mux_err)
                                    await _progress(f"Mixing generated audio failed ({mux_err}); continuing without it.")

                    await _progress("Uploading the final video…")
                    # Extracted while `out_path` still exists on disk — avoids
                    # re-downloading the video we just wrote to get a thumbnail.
                    thumb = await generate_video_thumbnail_from_file(ctx, out_path)
                    data = Path(out_path).read_bytes()
                    stored = await _store_merged(ctx, data)

                final = await update_item_success(db, record_id, url=stored)
                if thumb:
                    final = await set_item_fields(db, record_id, {"thumbnail_url": thumb}) or final
                final = await set_item_fields(db, record_id, {"is_favourite": True}) or final
                await broadcast_event(org_id, "completed", final, record_id, project_id, ctx.user_id)
                if request.project_id:
                    await touch_project(db, ctx.user_id, request.project_id)
            except Exception as e:  # noqa: BLE001 — surfaced on the item itself
                logger.exception("❌ Story merge failed")
                failed = await update_item_failed(db, record_id, f"Merge failed: {e}")
                await broadcast_event(org_id, "failed", failed, record_id, project_id, ctx.user_id)

    asyncio.create_task(_bg())

    return {
        "status": "pending",
        "project_id": project_id,
        "generation_id": generation_id,
        "message": "Merge started. Subscribe to /events/{project_id} for SSE updates.",
    }
